### ISSUE TITLE
SEGV in Vagrant  CI

### ISSUE THREAD

**Issue by kolyshkin** [opencontainers/runc#2353]
We have seen a few runc SIGSEGVs recently on a Vagrant CI. Let's collect them here.

**Comment by kolyshkin** [comment]
This was found once while running CI for opencontainers/runc#2335. The complete error is here:
https://travis-ci.org/github/opencontainers/runc/jobs/678293808

This has happened while running the integration test on checkpointing (https://github.com/opencontainers/runc/blob/cdce577dcf751b5c18e228cf33f72ad5d095d281/tests/integration/checkpoint.bats#L194).

The bug happened here: https://github.com/opencontainers/runc/blob/cdce577dcf751b5c18e228cf33f72ad5d095d281/libcontainer/container_linux.go#L1572

The except with the segv is here:
```
not ok 12 checkpoint and restore in external network namespace

(from function `testcontainer' in file tests/integration/helpers.bash, line 317,
 in test file tests/integration/checkpoint.bats, line 251)
  `testcontainer test_busybox running' failed

runc list (status=0):
ID          PID         STATUS      BUNDLE      CREATED     OWNER
runc spec (status=0):

runc run -d --console-socket /tmp/console.sock test_busybox (status=0):

runc state test_busybox (status=0):
{
  "ociVersion": "1.0.2",
  "id": "test_busybox",
  "pid": 58656,
  "status": "running",
  "bundle": "/tmp/busyboxtest",
  "rootfs": "/tmp/busyboxtest/rootfs",
  "created": "2020-04-22T19:30:44.618940367Z",
  "owner": ""
}

runc --criu /usr/local/sbin/criu checkpoint --work-path ./work-dir test_busybox (status=0):

(00.031958) mnt: 	368: 27:/ @ ./dev/shm
(00.036887) mnt: 	367: 26:/ @ ./dev/pts
(00.036902) mnt: 	366: 25:/ @ ./dev
(00.036905) mnt: Mount is not fully visible ./dev
(00.036940) mnt: 	mount has children ./dev
(00.036962) Error (criu/mount.c:1117): mnt: Can't create a temporary directory: Read-only file system

runc state test_busybox (status=1):
time="2020-04-22T19:30:44Z" level=error msg="container \"test_busybox\" does not exist"
container "test_busybox" does not exist

runc --criu /usr/local/sbin/criu restore -d --work-path ./work-dir --console-socket /tmp/console.sock test_busybox (status=0):

(00.047787) mnt: Switching to new ns to clean ghosts
(00.050034) Unlock network
(00.050045) Running network-unlock scripts
(00.050048) 	RPC
iptables-restore: line 5 failed
(00.052202) Error (criu/util.c:610): exited, status=1
ip6tables-restore: line 5 failed
(00.054215) Error (criu/util.c:610): exited, status=1

runc state test_busybox (status=0):
{
  "ociVersion": "1.0.2",
  "id": "test_busybox",
  "pid": 58717,
  "status": "running",
  "bundle": "/tmp/busyboxtest",
  "rootfs": "/tmp/busyboxtest/rootfs",
  "created": "2020-04-22T19:30:44.825464731Z",
  "owner": ""
}
old network namespace inode 4026532171
new network namespace inode 4026532171

runc --criu /usr/local/sbin/criu checkpoint --work-path ./work-dir test_busybox (status=0):

runc state test_busybox (status=1):
time="2020-04-22T19:30:45Z" level=error msg="container \"test_busybox\" does not exist"
container "test_busybox" does not exist

runc --criu /usr/local/sbin/criu restore -d --work-path ./work-dir --console-socket /tmp/console.sock test_busybox (status=2):
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x55f390d9501d]

goroutine 1 [running]:
runtime.throw(0x55f390f492cc, 0x5)
	/usr/lib/golang/src/runtime/panic.go:774 +0x74 fp=0xc000117d90 sp=0xc000117d60 pc=0x55f390b52934
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:401 +0x3e2 fp=0xc000117dc0 sp=0xc000117d90 pc=0x55f390b678d2
github.com/golang/protobuf/proto.(*unmarshalInfo).unmarshal(0xc0001b0000, 0xc00017e1c0, 0xc0001a4000, 0xa, 0xa000, 0x55f390b3118a, 0x20)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.3.5/proto/table_unmarshal.go:173 +0x76d fp=0xc000117f90 sp=0xc000117dc0 pc=0x55f390d9501d
github.com/golang/protobuf/proto.(*InternalMessageInfo).Unmarshal(0xc0001801a0, 0x55f3911add40, 0xc00017e1c0, 0xc0001a4000, 0xa, 0xa000, 0xc0001ae001, 0x0)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.3.5/proto/table_unmarshal.go:63 +0x68 fp=0xc000117ff0 sp=0xc000117f90 pc=0x55f390d94638
github.com/golang/protobuf/proto.(*Buffer).Unmarshal(0xc000118070, 0x55f3911add40, 0xc00017e1c0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.3.5/proto/decode.go:424 +0x1ee fp=0xc000118040 sp=0xc000117ff0 pc=0x55f390d72b4e
github.com/golang/protobuf/proto.Unmarshal(0xc0001a4000, 0xa, 0xa000, 0x55f3911add40, 0xc00017e1c0, 0x1000, 0x1000)
	/root/go/pkg/mod/github.com/golang/protobuf@v1.3.5/proto/decode.go:342 +0x172 fp=0xc0001180a8 sp=0xc000118040 pc=0x55f390d726b2
github.com/opencontainers/runc/libcontainer.(*linuxContainer).criuSwrk(0xc00015e1e0, 0x0, 0xc00018c000, 0x0, 0x7f1318338200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/vagrant/libcontainer/container_linux.go:1580 +0xca5 fp=0xc0001184d0 sp=0xc0001180a8 pc=0x55f390eb8615
github.com/opencontainers/runc/libcontainer.(*linuxContainer).checkCriuVersion(0xc00015e1e0, 0x2906, 0x7f1318338228, 0xc000118638)
	/vagrant/libcontainer/container_linux.go:805 +0x1c9 fp=0xc000118580 sp=0xc0001184d0 pc=0x55f390eb17a9
github.com/opencontainers/runc/libcontainer.(*linuxContainer).Restore(0xc00015e1e0, 0xc0000a57c0, 0xc00014f5f0, 0x0, 0x0)
	/vagrant/libcontainer/container_linux.go:1260 +0xbd fp=0xc000118bd0 sp=0xc000118580 pc=0x55f390eb4fcd
main.(*runner).run(0xc000119490, 0xc00015e000, 0x0, 0x0, 0x0)
	/vagrant/utils_linux.go:322 +0x8d5 fp=0xc0001193d8 sp=0xc000118bd0 pc=0x55f390f3bf35
main.startContainer(0xc0000d0840, 0xc0000f0400, 0x3, 0xc00014f5f0, 0x0, 0x0, 0x0)
	/vagrant/utils_linux.go:462 +0x43c fp=0xc000119520 sp=0xc0001193d8 pc=0x55f390f3d0bc
main.glob..func12(0xc0000d0840, 0x0, 0xc000124300)
	/vagrant/restore.go:112 +0x115 fp=0xc000119588 sp=0xc000119520 pc=0x55f390f40065
github.com/urfave/cli.HandleAction(0x55f3910f4700, 0x55f39119a460, 0xc0000d0840, 0xc0000d0840, 0x0)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:523 +0xc0 fp=0xc0001195b0 sp=0xc000119588 pc=0x55f390efbfc0
github.com/urfave/cli.Command.Run(0x55f390f4b95c, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55f390f5ffc3, 0x2e, 0x0, ...)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.1/command.go:174 +0x51e fp=0xc0001198d8 sp=0xc0001195b0 pc=0x55f390efcd2e
github.com/urfave/cli.(*App).Run(0xc000022380, 0xc0000200c0, 0xc, 0xc, 0x0, 0x0)
	/root/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:276 +0x71a fp=0xc000119c20 sp=0xc0001198d8 pc=0x55f390efa06a
main.main()
	/vagrant/main.go:151 +0xb29 fp=0xc000119f60 sp=0xc000119c20 pc=0x55f390f348d9
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:203 +0x226 fp=0xc000119fe0 sp=0xc000119f60 pc=0x55f390b542f6
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000119fe8 sp=0xc000119fe0 pc=0x55f390b80281

goroutine 7 [syscall]:
os/signal.signal_recv(0x55f3911ab4c0)
	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9e
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x24
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x43
(00.047787) mnt: Switching to new ns to clean ghosts
(00.050034) Unlock network
(00.050045) Running network-unlock scripts
(00.050048) 	RPC
iptables-restore: line 5 failed
(00.052202) Error (criu/util.c:610): exited, status=1
ip6tables-restore: line 5 failed
(00.054215) Error (criu/util.c:610): exited, status=1

runc state test_busybox (status=1):
time="2020-04-22T19:30:45Z" level=error msg="container \"test_busybox\" does not exist"
container "test_busybox" does not exist

runc list (status=0):
load container test_busybox: container "test_busybox" does not exist
ID          PID         STATUS      BUNDLE      CREATED     OWNER
```

**Comment by kolyshkin** [comment]
This one happened when running CI for #2342.

Travis logs here: 
https://travis-ci.org/github/opencontainers/runc/jobs/679155587

```
not ok 7 runc exec (limits + cgrouppath + permission on the cgroup dir) succeeds
# (in test file tests/integration/cgroups.bats, line 118)
#   `[ "$status" -eq 0 ]' failed with status 2
# runc list (status=0):
# ID          PID         STATUS      BUNDLE      CREATED     OWNER
# runc list (status=0):
# ID          PID         STATUS      BUNDLE      CREATED     OWNER
# runc list (status=0):
# ID          PID         STATUS      BUNDLE      CREATED     OWNER
# runc spec (status=0):
# 
# runc run -d --console-socket /tmp/console.sock test_cgroups_permissions (status=2):
# unexpected fault address 0x0
# fatal error: fault
# [signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x562a044cb2f9]
# 
# goroutine 1 [running]:
# runtime.throw(0x562a047012cc, 0x5)
# 	/usr/lib/golang/src/runtime/panic.go:774 +0x74 fp=0xc00012d8b8 sp=0xc00012d888 pc=0x562a0430a934
# runtime.sigpanic()
# 	/usr/lib/golang/src/runtime/signal_unix.go:401 +0x3e2 fp=0xc00012d8e8 sp=0xc00012d8b8 pc=0x562a0431f8d2
# encoding/json.byIndex.Less(0xc0001aa000, 0x2, 0x2, 0x1, 0x0, 0x1)
# 	/usr/lib/golang/src/encoding/json/encode.go:1064 +0x69 fp=0xc00012d908 sp=0xc00012d8e8 pc=0x562a044cb2f9
# encoding/json.(*byIndex).Less(0xc00000e1e0, 0x1, 0x0, 0x18)
# 	<autogenerated>:1 +0x64 fp=0xc00012d948 sp=0xc00012d908 pc=0x562a044d5294
# sort.insertionSort(0x562a04966920, 0xc00000e1e0, 0x0, 0x2)
# 	/usr/lib/golang/src/sort/sort.go:27 +0xc6 fp=0xc00012d988 sp=0xc00012d948 pc=0x562a0437b406
# sort.quickSort(0x562a04966920, 0xc00000e1e0, 0x0, 0x2, 0x4)
# 	/usr/lib/golang/src/sort/sort.go:209 +0x203 fp=0xc00012d9e0 sp=0xc00012d988 pc=0x562a0437c0f3
# sort.Sort(0x562a04966920, 0xc00000e1e0)
# 	/usr/lib/golang/src/sort/sort.go:218 +0x7b fp=0xc00012da20 sp=0xc00012d9e0 pc=0x562a0437c18b
# encoding/json.typeFields(0x562a0496e020, 0x562a048e6f80, 0x562a048e6f80, 0x0, 0x0, 0x7ff10c605f00)
# 	/usr/lib/golang/src/encoding/json/encode.go:1242 +0x1592 fp=0xc00012e448 sp=0xc00012da20 pc=0x562a044cc8f2
# encoding/json.cachedTypeFields(0x562a0496e020, 0x562a048e6f80, 0x199, 0x562a0496e020, 0x562a048e6f80, 0x0)
# 	/usr/lib/golang/src/encoding/json/encode.go:1278 +0xed fp=0xc00012e4c0 sp=0xc00012e448 pc=0x562a044cccdd
# encoding/json.(*decodeState).object(0xc000198188, 0x562a04884ee0, 0xc0000241c0, 0x16, 0xc0001981b0, 0x7b)
# 	/usr/lib/golang/src/encoding/json/decode.go:709 +0x292 fp=0xc00012e750 sp=0xc00012e4c0 pc=0x562a044bee92
# encoding/json.(*decodeState).value(0xc000198188, 0x562a04884ee0, 0xc0000241c0, 0x16, 0xc00012e830, 0x562a044d1f90)
# 	/usr/lib/golang/src/encoding/json/decode.go:429 +0x6f fp=0xc00012e7b8 sp=0xc00012e750 pc=0x562a044bd3ff
# encoding/json.(*decodeState).unmarshal(0xc000198188, 0x562a04884ee0, 0xc0000241c0, 0x0, 0xc000106301)
# 	/usr/lib/golang/src/encoding/json/decode.go:179 +0x1fd fp=0xc00012e840 sp=0xc00012e7b8 pc=0x562a044bc92d
# encoding/json.(*Decoder).Decode(0xc000198160, 0x562a04884ee0, 0xc0000241c0, 0x562a045a05da, 0xc0000c9900)
# 	/usr/lib/golang/src/encoding/json/stream.go:73 +0x168 fp=0xc00012e880 sp=0xc00012e840 pc=0x562a044d1c18
# github.com/opencontainers/runc/libcontainer.(*initProcess).getChildPid(0xc00019e000, 0xc000010038, 0x562a0495c6c0, 0xc000106360)
# 	/vagrant/libcontainer/process_linux.go:246 +0x9f fp=0xc00012e8d8 sp=0xc00012e880 pc=0x562a0467e64f
# github.com/opencontainers/runc/libcontainer.(*initProcess).start(0xc00019e000, 0x0, 0x0)
# 	/vagrant/libcontainer/process_linux.go:315 +0x2b3 fp=0xc00012ea40 sp=0xc00012e8d8 pc=0x562a0467eb93
# github.com/opencontainers/runc/libcontainer.(*linuxContainer).start(0xc0001781e0, 0xc0000b57c0, 0x0, 0x0)
# 	/vagrant/libcontainer/container_linux.go:343 +0x94 fp=0xc00012eb30 sp=0xc00012ea40 pc=0x562a04664c94
# github.com/opencontainers/runc/libcontainer.(*linuxContainer).Start(0xc0001781e0, 0xc0000b57c0, 0x0, 0x0)
# 	/vagrant/libcontainer/container_linux.go:240 +0xb1 fp=0xc00012ebb0 sp=0xc00012eb30 pc=0x562a04664251
# github.com/opencontainers/runc/libcontainer.(*linuxContainer).Run(0xc0001781e0, 0xc0000b57c0, 0x0, 0x101)
# 	/vagrant/libcontainer/container_linux.go:250 +0x3b fp=0xc00012ebe0 sp=0xc00012ebb0 pc=0x562a0466439b
# main.(*runner).run(0xc00012f4a0, 0xc000178000, 0x0, 0x0, 0x0)
# 	/vagrant/utils_linux.go:324 +0xcd8 fp=0xc00012f3e8 sp=0xc00012ebe0 pc=0x562a046f4278
# main.startContainer(0xc0000e6b00, 0xc0000aa400, 0x2, 0x0, 0x0, 0x5, 0x562a04966a60)
# 	/vagrant/utils_linux.go:462 +0x43c fp=0xc00012f530 sp=0xc00012f3e8 pc=0x562a046f4ffc
# main.glob..func13(0xc0000e6b00, 0x0, 0xc0000be880)
# 	/vagrant/run.go:76 +0xb0 fp=0xc00012f588 sp=0xc00012f530 pc=0x562a046f8150
# github.com/urfave/cli.HandleAction(0x562a048ac460, 0x562a049521c8, 0xc0000e6b00, 0xc0000e6b00, 0x0)
# 	/vagrant/vendor/github.com/urfave/cli/app.go:523 +0xc0 fp=0xc00012f5b0 sp=0xc00012f588 pc=0x562a046b3f00
# github.com/urfave/cli.Command.Run(0x562a04700453, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x562a0470e849, 0x1a, 0x0, ...)
# 	/vagrant/vendor/github.com/urfave/cli/command.go:174 +0x51e fp=0xc00012f8d8 sp=0xc00012f5b0 pc=0x562a046b4c6e
# github.com/urfave/cli.(*App).Run(0xc0000a01c0, 0xc0000aa000, 0x8, 0x8, 0x0, 0x0)
# 	/vagrant/vendor/github.com/urfave/cli/app.go:276 +0x71a fp=0xc00012fc20 sp=0xc00012f8d8 pc=0x562a046b1faa
# main.main()
# 	/vagrant/main.go:151 +0xb29 fp=0xc00012ff60 sp=0xc00012fc20 pc=0x562a046ec819
# runtime.main()
# 	/usr/lib/golang/src/runtime/proc.go:203 +0x226 fp=0xc00012ffe0 sp=0xc00012ff60 pc=0x562a0430c2f6
# runtime.goexit()
# 	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00012ffe8 sp=0xc00012ffe0 pc=0x562a04338281
# 
# goroutine 5 [IO wait]:
# internal/poll.runtime_pollWait(0x7ff109ba5d68, 0x72, 0xffffffffffffffff)
# 	/usr/lib/golang/src/runtime/netpoll.go:184 +0x57
# internal/poll.(*pollDesc).wait(0xc00006c438, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
# 	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:87 +0x47
# internal/poll.(*pollDesc).waitRead(...)
# 	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:92
# internal/poll.(*FD).Read(0xc00006c420, 0xc0001a4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
# 	/usr/lib/golang/src/internal/poll/fd_unix.go:169 +0x1d1
# os.(*File).read(...)
# 	/usr/lib/golang/src/os/file_unix.go:259
# os.(*File).Read(0xc000010048, 0xc0001a4000, 0x1000, 0x1000, 0x562a04885aa0, 0xc000161da0, 0xc0000cfde0)
# 	/usr/lib/golang/src/os/file.go:116 +0x73
# bufio.(*Reader).fill(0xc0000cff68)
# 	/usr/lib/golang/src/bufio/bufio.go:100 +0x105
# bufio.(*Reader).ReadSlice(0xc0000cff68, 0x562a04655c0a, 0xc0000c0000, 0x5, 0xc0000c3b20, 0x19, 0x0)
# 	/usr/lib/golang/src/bufio/bufio.go:359 +0x3f
# bufio.(*Reader).ReadBytes(0xc0000cff68, 0xa, 0x36, 0x36, 0x36, 0x0, 0x0)
# 	/usr/lib/golang/src/bufio/bufio.go:437 +0x75
# github.com/opencontainers/runc/libcontainer/logs.ForwardLogs(0x562a0495d020, 0xc000010048)
# 	/vagrant/libcontainer/logs/logs.go:32 +0x82
# created by github.com/opencontainers/runc/libcontainer.(*initProcess).forwardChildLogs
# 	/vagrant/libcontainer/process_linux.go:520 +0x51
# 
# goroutine 20 [syscall]:
# os/signal.signal_recv(0x562a04963220)
# 	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9e
# os/signal.loop()
# 	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x24
# created by os/signal.init.0
# 	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x43
# runc list (status=0):
# load container test_cgroups_permissions: container "test_cgroups_permissions" does not exist
# ID          PID         STATUS      BUNDLE      CREATED     OWNER
# runc list (status=0):
# load container test_cgroups_permissions: container "test_cgroups_permissions" does not exist
# ID          PID         STATUS      BUNDLE      CREATED     OWNER
# runc list (status=0):
# load container test_cgroups_permissions: container "test_cgroups_permissions" does not exist
# ID          PID         STATUS      BUNDLE      CREATED     OWNER
```

**Comment by AkihiroSuda** [comment]
Closing as we are not seeing this recently
