### ISSUE TITLE
SIGSEV when parsing invalid configuration

### ISSUE THREAD

**Issue by RenaudWasTaken** [opencontainers/runc#2392]
Hello!

While writing some tests for runc, I stumbled upon a SIGSEV in how runc validates the spec.
This spec is very much invalid, but runc probably should just return an error :)

See below:
```
➜  cat ./bundle/config.json
{
        "ociVersion": "1.0.0"
},
        "process": {
        }

➜ sudo runc run -b . ctr-name
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x56384d4e7aa8]

goroutine 1 [running]:
main.validateProcessSpec(0x0, 0x56384d7c98a0, 0xc0000100d0)
        /home/renaud/go-1.14/src/github.com/opencontainers/runc/utils_linux.go:382 +0x28
main.loadSpec(0x56384d4f8f89, 0xb, 0x0, 0x0, 0x0)
        /home/renaud/go-1.14/src/github.com/opencontainers/runc/spec.go:132 +0x34a
main.setupSpec(0xc00014e840, 0x0, 0x0, 0x0)
        /home/renaud/go-1.14/src/github.com/opencontainers/runc/utils.go:65 +0x75
main.glob..func13(0xc00014e840, 0x0, 0xc000178480)
        /home/renaud/go-1.14/src/github.com/opencontainers/runc/run.go:72 +0x85
github.com/urfave/cli.HandleAction(0x56384d7f0be0, 0x56384d88c100, 0xc00014e840, 0xc00014e840, 0x0)
        /home/renaud/go-1.14/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:523 +0x11c
github.com/urfave/cli.Command.Run(0x56384d4f300d, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x56384d5015f0, 0x1a, 0x0, ...)
        /home/renaud/go-1.14/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:174 +0x570
github.com/urfave/cli.(*App).Run(0xc000236000, 0xc0000200a0, 0x5, 0x5, 0x0, 0x0)
        /home/renaud/go-1.14/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:276 +0x7b0
main.main()
        /home/renaud/go-1.14/src/github.com/opencontainers/runc/main.go:151 +0xb29
```

Hope this helps!

**Comment by cyphar** [comment]
There's a `spec != nil` check missing somewhere there.

**Comment by JFHwang** [comment]
Hello!
I am new to contributing to open source, but if possible, I would like to try to tackle this issue.
