### ISSUE TITLE
terminal: true with no stdin causes container startup failure

### ISSUE THREAD

**Issue by cyphar** [opencontainers/runc#2485]
If you try to run a container that has `"terminal": true` configured in non-detached mode with a dummy stdin (like `/dev/null`), you get errors:

```
% sudo runc run -b bundle ctr </dev/null
WARN[0000] exit status 2                                
ERRO[0000] container_linux.go:367: starting container process caused: process_linux.go:459: container init caused: 
```

Found as part of opencontainers/umoci#296.

**Comment by kolyshkin** [comment]
Most probably caused by assumption that fd 0 is a terminal (in `libcontainer/system.Setctty()`). I barely remember it was causing a real error before, now it's some weirdness:

With the following patch:
```diff
diff --git a/libcontainer/container_linux.go b/libcontainer/container_linux.go
index e958d159..f7cf9a64 100644
--- a/libcontainer/container_linux.go
+++ b/libcontainer/container_linux.go
@@ -358,7 +358,7 @@ func (c *linuxContainer) start(process *Process) error {
        if err := parent.start(); err != nil {
                // terminate the process to ensure that it properly is reaped.
                if err := ignoreTerminateErrors(parent.terminate()); err != nil {
-                       logrus.Warn(err)
+                       logrus.Warnf("terminate parent: %v", err)
                }
                return newSystemErrorWithCause(err, "starting container process")
        }
diff --git a/libcontainer/standard_init_linux.go b/libcontainer/standard_init_linux.go
index f5be67c0..7002086a 100644
--- a/libcontainer/standard_init_linux.go
+++ b/libcontainer/standard_init_linux.go
@@ -100,6 +100,7 @@ func (l *linuxStandardInit) Init() error {
                }
        }
 
+       return errors.New("after CreateConsole")
        // Finish the rootfs setup.
        if l.config.Config.Namespaces.Contains(configs.NEWNS) {
                if err := finalizeRootfs(l.config.Config); err != nil {
```

it breaks in 3 different ways (in 3 identical consecutive runs):

```console
[kir@kir-rhat tst]$ sudo ../runc --debug run xx44 < /dev/null
DEBU[0000] nsexec:601 nsexec started                    
DEBU[0000] child process in init()                      
DEBU[0000] logging has already been configured          
DEBU[0000] log pipe has been closed: EOF                
WARN[0000] terminate parent: exit status 2              
ERRO[0000] container_linux.go:363: starting container process caused: process_linux.go:450: container init caused: after CreateConsole 
[kir@kir-rhat tst]$ sudo ../runc --debug run xx44 < /dev/null
DEBU[0000] nsexec:601 nsexec started                    
DEBU[0000] child process in init()                      
DEBU[0000] logging has already been configured          
DEBU[0000] log pipe has been closed: EOF                
WARN[0000] terminate parent: exit status 2              
ERRO[0000] container_linux.go:363: starting container process caused: process_linux.go:450: container init caused:  
[kir@kir-rhat tst]$ sudo ../runc --debug run xx44 < /dev/null
DEBU[0000] nsexec:601 nsexec started                    
DEBU[0000] child process in init()                      
DEBU[0000] logging has already been configured          
panic: No error following JSON procError payload.

goroutine 1 [running]:
github.com/opencontainers/runc/libcontainer.parseSync(0x55a649c91080, 0xc000206b18, 0xc000252a78, 0xc0002a83c0, 0x0)
	/home/kir/go/src/github.com/opencontainers/runc/libcontainer/sync.go:93 +0x2f4
github.com/opencontainers/runc/libcontainer.(*initProcess).start(0xc00029d5f0, 0x0, 0x0)
	/home/kir/go/src/github.com/opencontainers/runc/libcontainer/process_linux.go:373 +0x479
github.com/opencontainers/runc/libcontainer.(*linuxContainer).start(0xc0002a81e0, 0xc00022cf00, 0x0, 0xc000262d90)
	/home/kir/go/src/github.com/opencontainers/runc/libcontainer/container_linux.go:358 +0x94
github.com/opencontainers/runc/libcontainer.(*linuxContainer).Start(0xc0002a81e0, 0xc00022cf00, 0x0, 0x0)
	/home/kir/go/src/github.com/opencontainers/runc/libcontainer/container_linux.go:255 +0x94
github.com/opencontainers/runc/libcontainer.(*linuxContainer).Run(0xc0002a81e0, 0xc00022cf00, 0x0, 0x1)
	/home/kir/go/src/github.com/opencontainers/runc/libcontainer/container_linux.go:265 +0x3b
main.(*runner).run(0xc000253518, 0xc0002a8000, 0x0, 0x0, 0x0)
	/home/kir/go/src/github.com/opencontainers/runc/utils_linux.go:323 +0xce0
main.startContainer(0xc00027e160, 0xc00020e300, 0x2, 0x0, 0x0, 0xc000218998, 0x55a649c9a660)
	/home/kir/go/src/github.com/opencontainers/runc/utils_linux.go:464 +0x43c
main.glob..func13(0xc00027e160, 0x0, 0xc000210380)
	/home/kir/go/src/github.com/opencontainers/runc/run.go:76 +0xb0
github.com/urfave/cli.HandleAction(0x55a649be8fc0, 0x55a649c86230, 0xc00027e160, 0xc00027e160, 0x0)
	/home/kir/go/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:523 +0x11c
github.com/urfave/cli.Command.Run(0x55a649ae7450, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55a649af5c2b, 0x1a, 0x0, ...)
	/home/kir/go/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:174 +0x570
github.com/urfave/cli.(*App).Run(0xc000278000, 0xc0000b6000, 0x4, 0x4, 0x0, 0x0)
	/home/kir/go/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:276 +0x7b0
main.main()
	/home/kir/go/src/github.com/opencontainers/runc/main.go:151 +0xb29
```

Might be caused by https://github.com/opencontainers/runc/pull/2229

**Comment by cyphar** [comment]
We need to add more debugging information so that `--debug` is actually useful. Trying to narrow down this bug was kind of the goal of #2460.

**Comment by kolyshkin** [comment]
I looked a bit more into it, it seems the `runc init` dies as it receives SIGHUP. If we choose to ignore SIGHUP, then it errors out like this:

> ERRO[0000] provided file is not a console               

which, I think, was the way it worked before adding hooks. 

The error comes from containerd/console and is caused by the following code in tty.go:

```go
        // set raw mode to stdin and also handle interrupt
        stdin, err := console.ConsoleFromFile(os.Stdin)
```

Obviously, os.Stdin is not a console :)

I am not really sure what to do about it, and my analysis might be entirely wrong.

**Comment by kolyshkin** [comment]
Not sure what to do about this one

> stdin, err := console.ConsoleFromFile(os.Stdin)

I guess that if stdin is not a terminal (because it is redirected), we should try stdout and stderr -- if neither of the three is a terminal, either bail out, or open and use `/dev/tty` which should be our controlling terminal. Although I'm not sure we should do anything with a terminal if all of the std{in,out,err} are redirected.

**Comment by kolyshkin** [comment]
Almost made it working, but it needs this first as the code in tty.go calls `console.Current()`: https://github.com/containerd/console/pull/37
