### ISSUE TITLE
runc and systemd

### ISSUE THREAD

**Issue by hqhq** [opencontainers/runc#325]
Hi all,

I noticed that runc is only using cgroupfs no matter if the host support systemd or not, wondering if this is intentional?

I was trying to enable systemd by a simple change:
```
diff --git a/utils.go b/utils.go
index 151705e..23b7df0 100644
--- a/utils.go
+++ b/utils.go
@@ -104,7 +104,7 @@ func loadFactory(context *cli.Context) (libcontainer.Factory, error) {
        if err != nil {
                return nil, err
        }
-       return libcontainer.New(abs, libcontainer.Cgroupfs, func(l *libcontainer.LinuxFactory) error
+       return libcontainer.New(abs, libcontainer.SystemdCgroups, func(l *libcontainer.LinuxFactory)
                l.CriuPath = context.GlobalString("criu")
                return nil
        })
```

But got panic with `runc start`, the running goroution is:
```
# runc start
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x61e808]

goroutine 1 [running]:
github.com/coreos/go-systemd/dbus.(*Conn).startJob(0x0, 0x0, 0x800410, 0x29, 0xc20800b660, 0x2, 0x2, 0x0, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods.go:47 +0xd8
github.com/coreos/go-systemd/dbus.(*Conn).StopUnit(0x0, 0xc20802be10, 0xc, 0x791da0, 0x7, 0x0, 0xb55a78, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods.go:99 +0x1a1
github.com/opencontainers/runc/libcontainer/cgroups/systemd.(*Manager).Destroy(0xc20800b3e0, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go:277 +0xd2
github.com/opencontainers/runc/libcontainer.(*linuxContainer).Destroy(0xc20806a990, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/libcontainer/container_linux.go:246 +0x33c
main.destroy(0x7f55324059c0, 0xc20806a990)
        /go/src/github.com/opencontainers/runc/start.go:151 +0x127
github.com/coreos/go-systemd/dbus.(*Conn).startJob(0x0, 0x0, 0x8098f0, 0x33, 0xc208035280, 0x4, 0x4, 0x0, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods.go:47 +0xd8
github.com/coreos/go-systemd/dbus.(*Conn).StartTransientUnit(0x0, 0xc20802bd70, 0xc, 0x791da0, 0x7, 0xc20806d560, 0x6, 0x6, 0x0, 0xc20802bda4, ...)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods.go:137 +0x2ba
github.com/opencontainers/runc/libcontainer/cgroups/systemd.(*Manager).Apply(0xc20800b3e0, 0xc2d, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go:201 +0xcab
github.com/opencontainers/runc/libcontainer.(*initProcess).start(0xc208050dc0, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/libcontainer/process_linux.go:195 +0x2e9
github.com/opencontainers/runc/libcontainer.(*linuxContainer).Start(0xc20806a990, 0xc20801f930, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/libcontainer/container_linux.go:107 +0x1b9
main.startContainer(0xc208064380, 0xc20807a0f0, 0xc208058280, 0x0, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/start.go:124 +0x84e
main.func·009(0xc208064380)
        /go/src/github.com/opencontainers/runc/start.go:56 +0x37b
github.com/codegangsta/cli.Command.Run(0x792c60, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7d34d0, 0x1a, 0x0, ...)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:118 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc20807a000, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:154 +0xd04
main.main()
        /go/src/github.com/opencontainers/runc/main.go:88 +0x6fd
```

I haven't figured out what caused this panic, maybe I can get some help here, see if anyone tried this before?

**Comment by crosbymichael** [comment]
Ya, it's intentional for now.  systemd cgroups are not good and just add complexity.  We can get the same outcome by runc's default functionality of nesting it'self in the current cgroup.  Here is a sample unit file and what the cgroups look like for one of my containers.

```systemd
[Unit]
Description=Counter Strike Global Offensive
Documentation=http://counter-strike.net
After=network.target

[Service]
CPUQuota=200%
MemoryLimit=1256M
ExecStart=/usr/local/bin/runc start
Restart=on-failure
WorkingDirectory=/containers/csgo

[Install]
WantedBy=multi-user.target
```

```bash
root@sfo1:~# systemctl status csgo
● csgo.service - Counter Strike Global Offensive
   Loaded: loaded (/lib/systemd/system/csgo.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2015-10-04 14:35:58 EDT; 1 weeks 2 days ago
     Docs: http://counter-strike.net
 Main PID: 4708 (runc)
   Memory: 251.1M (limit: 1.2G)
   CGroup: /system.slice/csgo.service
           ├─4708 /usr/local/bin/runc start
           └─4714 ./srcds_linux -game csgo -console -usercon -tickrate 128 +game_type 0 +game_mode 1 +mapgroup mg_...

Oct 14 12:16:40 sfo1.gamecontainers.com runc[4708]: Your server needs to be restarted in order to receive the ...ate.
Oct 14 12:16:40 sfo1.gamecontainers.com runc[4708]: [21B blob data]
Oct 14 12:16:40 sfo1.gamecontainers.com runc[4708]: Your server needs to be restarted in order to receive the ...ate.
Oct 14 12:16:40 sfo1.gamecontainers.com runc[4708]: [21B blob data]
Oct 14 12:16:40 sfo1.gamecontainers.com runc[4708]: Your server needs to be restarted in order to receive the ...ate.
Oct 14 12:16:40 sfo1.gamecontainers.com runc[4708]: [21B blob data]
Oct 14 12:16:40 sfo1.gamecontainers.com runc[4708]: Your server needs to be restarted in order to receive the ...ate.
Oct 14 12:16:40 sfo1.gamecontainers.com runc[4708]: [21B blob data]
Oct 14 12:16:40 sfo1.gamecontainers.com runc[4708]: Your server needs to be restarted in order to receive the ...ate.
Oct 14 12:16:40 sfo1.gamecontainers.com runc[4708]: [21B blob data]
Hint: Some lines were ellipsized, use -l to show in full.


root@sfo1:~# cat /proc/4714/cgroup 
10:devices:/system.slice/csgo.service/csgo
9:freezer:/system.slice/csgo.service/csgo
8:net_cls,net_prio:/system.slice/csgo.service/csgo
7:cpuset:/system.slice/csgo.service/csgo
6:perf_event:/system.slice/csgo.service/csgo
5:cpu,cpuacct:/system.slice/csgo.service/csgo
4:memory:/system.slice/csgo.service/csgo
3:blkio:/system.slice/csgo.service/csgo
2:hugetlb:/system.slice/csgo.service/csgo
1:name=systemd:/system.slice/csgo.service
```

Perfect ;)

**Comment by vishh** [comment]
@crosbymichael: :clap: +1

**Comment by crosbymichael** [comment]
I did this by adding 4 lines to runc.

https://github.com/opencontainers/runc/blob/master/spec.go#L443

**Comment by crosbymichael** [comment]
Going to close this now because of the support that we do have so that runc can nest itself into the systemd created cgroups or you can now profile the cgroup path to runc that was setup by systemd.
