### ISSUE TITLE
Runc init disk sleep but cgroup stat is thraw, and runc exec hang

### ISSUE THREAD

**Issue by b675987273** [opencontainers/runc#3663]
the init process stack, well it is differen between the #27xx issue because the cgroup stat is thraw.Then I do not konw how analyz next. Any tool or method i need to know in addition?
```shell
:/proc/11952/task/11952
# cat stack
[<0>] __refrigerator+0x3f/0x160
[<0>] get_signal+0x573/0x590
[<0>] do_signal+0x36/0x610
[<0>] exit_to_usermode_loop+0x89/0xf0
[<0>] prepare_exit_to_usermode+0x90/0xc0
[<0>] retint_user+0x8/0x8
[<0>] 0xffffffffffffffff
```
the runc version
```shell
# runc -v
runc version 1.1.2
commit: v1.1.2-0-ga916309
spec: 1.0.2-dev
go: go1.17.11
libseccomp: 2.3.1
```
the runc exec cmdline
```shell
:/proc/11933
# cat cmdline
runc--root/var/run/docker/runtime-runc/moby--log/run/containerd/io.containerd.runtime.v1.linux/moby/b5ad16dee95550f0246fc055f2ccd1e1a27055ae401d2de2808a4887e1d5d149/log.json--log-formatjson--systemd-cgroupexec--process/tmp/runc-process418749423--detach--pid-file/run/containerd/io.containerd.runtime.v1.linux/moby/b5ad16dee95550f0246fc055f2ccd1e1a27055ae401d2de2808a4887e1d5d149/2e16a85c74cd2df5bc074d3b0f4011e7696da3df5e2c320cbbe5430efe1421ed.pidb5ad16dee95550f0246fc055f2ccd1e1a27055ae401d2de2808a4887e1d5d14
```
here is the runc exe's strack
```shell
# cat runexecstrack.log
Thread 7 (Thread 0x7f58b7987700 (LWP 13595)):
#0  runtime.futex () at runtime/sys_linux_amd64.s:520
#1  0x0000562af293eb51 in runtime.futexsleep (addr=<optimized out>, val=<optimized out>, ns=<optimized out>) at runtime/os_linux.go:50
#2  0x0000562af291a905 in runtime.notetsleep_internal (n=0x562af332e698 <runtime.sched+280>, ns=60000000000) at runtime/lock_futex.go:202
#3  0x0000562af291aa54 in runtime.notetsleep (n=0xfffffffffffffdfc, ns=0) at runtime/lock_futex.go:225
#4  0x0000562af29504db in runtime.sysmon () at runtime/proc.go:5374
#5  0x0000562af2947db5 in runtime.mstart1 () at runtime/proc.go:1407
#6  0x0000562af2947cf9 in runtime.mstart0 () at runtime/proc.go:1365
#7  0x0000562af2971025 in runtime.mstart () at runtime/asm_amd64.s:248
#8  0x0000562af2975785 in runtime.mstart () at <autogenerated>:1
#9  0x0000562af2cd6e32 in crosscall_amd64 () at gcc_amd64.S:40
#10 0x00007f58b7987700 in ?? ()
#11 0x0000000000000000 in ?? ()
Thread 6 (Thread 0x7f58b7186700 (LWP 13596)):
#0  runtime.epollwait () at runtime/sys_linux_amd64.s:666
#1  0x0000562af293e7fc in runtime.netpoll (delay=<optimized out>) at runtime/netpoll_epoll.go:127
#2  0x0000562af294a5f5 in runtime.findrunnable () at runtime/proc.go:2947
#3  0x0000562af294b7f9 in runtime.schedule () at runtime/proc.go:3367
#4  0x0000562af294bd4d in runtime.park_m (gp=0xc000202340) at runtime/proc.go:3516
#5  0x0000562af29710a5 in runtime.mcall () at runtime/asm_amd64.s:307
#6  0x0000000000000000 in ?? ()
Thread 5 (Thread 0x7f58b6985700 (LWP 13597)):
#0  runtime.futex () at runtime/sys_linux_amd64.s:520
#1  0x0000562af293ead6 in runtime.futexsleep (addr=0xfffffffffffffe00, val=0, ns=94742458618115) at runtime/os_linux.go:44
#2  0x0000562af291a9c7 in runtime.notetsleep_internal (n=0x562af335cf00 <runtime.sig>, ns=-1) at runtime/lock_futex.go:183
#3  0x0000562af291aae5 in runtime.notetsleepg (n=0x562af335cf00 <runtime.sig>, ns=-1) at runtime/lock_futex.go:237
#4  0x0000562af296fcf8 in os/signal.signal_recv () at runtime/sigqueue.go:169
#5  0x0000562af2caeeb9 in os/signal.loop () at os/signal/signal_unix.go:24
#6  0x0000562af2973361 in runtime.goexit () at runtime/asm_amd64.s:1581
#7  0x0000000000000000 in ?? ()
Thread 4 (Thread 0x7f58b6184700 (LWP 13598)):
#0  runtime.futex () at runtime/sys_linux_amd64.s:520
#1  0x0000562af293ead6 in runtime.futexsleep (addr=0xfffffffffffffe00, val=0, ns=94742458618115) at runtime/os_linux.go:44
#2  0x0000562af291a7c7 in runtime.notesleep (n=0xfffffffffffffe00) at runtime/lock_futex.go:160
#3  0x0000562af29492f1 in runtime.templateThread () at runtime/proc.go:2385
#4  0x0000562af2947db5 in runtime.mstart1 () at runtime/proc.go:1407
#5  0x0000562af2947cf9 in runtime.mstart0 () at runtime/proc.go:1365
#6  0x0000562af2971025 in runtime.mstart () at runtime/asm_amd64.s:248
#7  0x0000562af2975785 in runtime.mstart () at <autogenerated>:1
#8  0x0000562af2cd6e32 in crosscall_amd64 () at gcc_amd64.S:40
#9  0x00007f58b6184700 in ?? ()
#10 0x0000000000000000 in ?? ()
Thread 3 (Thread 0x7f58b5983700 (LWP 13600)):
#0  runtime.futex () at runtime/sys_linux_amd64.s:520
#1  0x0000562af293ead6 in runtime.futexsleep (addr=0xfffffffffffffe00, val=0, ns=94742458618115) at runtime/os_linux.go:44
#2  0x0000562af291a7c7 in runtime.notesleep (n=0xfffffffffffffe00) at runtime/lock_futex.go:160
#3  0x0000562af2947eaa in runtime.mPark () at runtime/proc.go:1439
#4  0x0000562af29493f8 in runtime.stopm () at runtime/proc.go:2408
#5  0x0000562af294a8c5 in runtime.findrunnable () at runtime/proc.go:2984
#6  0x0000562af294b7f9 in runtime.schedule () at runtime/proc.go:3367
#7  0x0000562af2947def in runtime.mstart1 () at runtime/proc.go:1414
#8  0x0000562af2947cf9 in runtime.mstart0 () at runtime/proc.go:1365
#9  0x0000562af2971025 in runtime.mstart () at runtime/asm_amd64.s:248
#10 0x0000562af2975785 in runtime.mstart () at <autogenerated>:1
#11 0x0000562af2cd6e32 in crosscall_amd64 () at gcc_amd64.S:40
#12 0x00007f58b5983700 in ?? ()
#13 0x0000000000000000 in ?? ()
Thread 2 (Thread 0x7f58b5182700 (LWP 13601)):
#0  syscall.Syscall () at syscall/asm_linux_amd64.s:26
#1  0x0000562af29bbc0d in syscall.read (fd=-512, p=...) at syscall/zsyscall_linux_amd64.go:687
#2  0x0000562af29d72a5 in syscall.Read (fd=8, n=<optimized out>, err=..., p=...) at syscall/syscall_unix.go:189
#3  internal/poll.ignoringEINTRIO (fd=8, fn=<optimized out>, p=...) at internal/poll/fd_unix.go:582
#4  internal/poll.(*FD).Read (fd=0xc000216000, p=..., ~r1=<optimized out>, ~r2=...) at internal/poll/fd_unix.go:163
#5  0x0000562af29e055e in os.(*File).read (f=0xc000214000, b=..., n=<optimized out>, err=...) at os/file.go:119
#6  os.(*File).Read (f=0xc000214000, b=...) at os/file.go:119
#7  0x0000562af2ab28df in encoding/json.(*Decoder).refill (dec=0xc000186a00) at encoding/json/stream.go:165
#8  0x0000562af2ab24fb in encoding/json.(*Decoder).readValue (dec=0xfffffffffffffe00) at encoding/json/stream.go:140
#9  0x0000562af2ab2238 in encoding/json.(*Decoder).Decode (dec=0xc000186a00, v=...) at encoding/json/stream.go:63
#10 0x0000562af2c49b06 in github.com/opencontainers/runc/libcontainer.parseSync (pipe=..., fn={void (github.com/opencontainers/runc/libcontainer.syncT *, error *)} 0xc000116708) at github.com/opencontainers/runc/libcontainer/sync.go:101
#11 0x0000562af2c39e6f in github.com/opencontainers/runc/libcontainer.(*setnsProcess).start (p=0xc00021c0a0, retErr=...) at github.com/opencontainers/runc/libcontainer/process_linux.go:168
#12 0x0000562af2c23174 in github.com/opencontainers/runc/libcontainer.(*linuxContainer).start (c=0xc000092600, process=0xc000186780, retErr=...) at github.com/opencontainers/runc/libcontainer/container_linux.go:354
#13 0x0000562af2c22605 in github.com/opencontainers/runc/libcontainer.(*linuxContainer).Start (c=0xc000092600, process=0xc000186780, ~r1=...) at github.com/opencontainers/runc/libcontainer/container_linux.go:239
#14 0x0000562af2c227e5 in github.com/opencontainers/runc/libcontainer.(*linuxContainer).Run (c=0xfffffffffffffe00, process=0xc000186780) at github.com/opencontainers/runc/libcontainer/container_linux.go:249
#15 0x0000562af2ccc832 in main.(*runner).run (r=0xc0001175c8, config=0xc0000201e0, ~r1=<optimized out>, ~r2=...) at github.com/opencontainers/runc/utils_linux.go:293
#16 0x0000562af2cc299b in main.execProcess (context=0xc000098840) at github.com/opencontainers/runc/exec.go:188
#17 0x0000562af2cce84f in main.glob..func5 (context=0xc000098840) at github.com/opencontainers/runc/exec.go:106
#18 0x0000562af2c906e8 in github.com/urfave/cli.HandleAction (action=..., context=<optimized out>) at github.com/urfave/cli@v1.22.1/app.go:523
#19 0x0000562af2c914ba in github.com/urfave/cli.Command.Run (c=..., ctx=0xc0000986e0, err=...) at github.com/urfave/cli@v1.22.1/command.go:174
#20 0x0000562af2c8e94c in github.com/urfave/cli.(*App).Run (a=0xc0000ba540, arguments=..., err=...) at github.com/urfave/cli@v1.22.1/app.go:276
#21 0x0000562af2cc58dc in main.main () at github.com/opencontainers/runc/main.go:162
Thread 1 (Thread 0x7f58deece740 (LWP 13594)):
#0  runtime.futex () at runtime/sys_linux_amd64.s:520
#1  0x0000562af293ead6 in runtime.futexsleep (addr=0xfffffffffffffe00, val=0, ns=94742458618115) at runtime/os_linux.go:44
#2  0x0000562af291a7c7 in runtime.notesleep (n=0xfffffffffffffe00) at runtime/lock_futex.go:160
#3  0x0000562af2947eaa in runtime.mPark () at runtime/proc.go:1439
#4  0x0000562af2949b25 in runtime.stoplockedm () at runtime/proc.go:2602
#5  0x0000562af294b5fd in runtime.schedule () at runtime/proc.go:3299
#6  0x0000562af294bd4d in runtime.park_m (gp=0xc0001981a0) at runtime/proc.go:3516
#7  0x0000562af29710a5 in runtime.mcall () at runtime/asm_amd64.s:307
#8  0x0000562af297586b in runtime.newproc (siz=-224980955, fn=0x562af2970fdf <runtime.rt0_go+319>) at <autogenerated>:1
#9  0x0000000000000000 in ?? ()
```

**Comment by b675987273** [comment]
ok, When i move the runc init in D state to a new thawed cgroup freezer, runc init recover and run to the end. So i think maybe there are some bug in our kenel.
