### ISSUE TITLE
0.0.9: Hanging test `libcontainer/nsenter/nsenter_test.go`

### ISSUE THREAD

**Issue by onlyjob** [opencontainers/runc#692]
`go test` hangs for 10 minutes on `libcontainer/nsenter/nsenter_test.go` before termination:

~~~~
nsenter: Failed to setns to /proc/83954/ns/pid: Operation not permitted 
SIGQUIT: quit 
PC=0x4970b2 m=0 

goroutine 21 [syscall]: 
syscall.Syscall(0x0, 0x4, 0xc8200a2400, 0x200, 0xc820073b00, 0x30, 0x30) 
        /usr/lib/go/src/syscall/asm_linux_amd64.s:18 +0x5 fp=0xc820034900 sp=0xc8200348f8 
syscall.read(0x4, 0xc8200a2400, 0x200, 0x200, 0x30, 0x0, 0x0) 
        /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f fp=0xc820034940 sp=0xc820034900 
syscall.Read(0x4, 0xc8200a2400, 0x200, 0x200, 0xc8200a2400, 0x0, 0x0) 
        /usr/lib/go/src/syscall/syscall_unix.go:161 +0x4d fp=0xc820034980 sp=0xc820034940 
os.(*File).read(0xc8200820c8, 0xc8200a2400, 0x200, 0x200, 0x0, 0x0, 0x0) 
        /usr/lib/go/src/os/file_unix.go:228 +0x53 fp=0xc8200349c0 sp=0xc820034980 
os.(*File).Read(0xc8200820c8, 0xc8200a2400, 0x200, 0x200, 0x0, 0x0, 0x0) 
        /usr/lib/go/src/os/file.go:95 +0x8a fp=0xc820034a18 sp=0xc8200349c0 
encoding/json.(*Decoder).refill(0xc820077380, 0x0, 0x0) 
        /usr/lib/go/src/encoding/json/stream.go:152 +0x287 fp=0xc820034ad0 sp=0xc820034a18 
encoding/json.(*Decoder).readValue(0xc820077380, 0x1, 0x0, 0x0) 
        /usr/lib/go/src/encoding/json/stream.go:128 +0x413 fp=0xc820034b80 sp=0xc820034ad0 
encoding/json.(*Decoder).Decode(0xc820077380, 0x65d460, 0xc8200820f0, 0x0, 0x0) 
        /usr/lib/go/src/encoding/json/stream.go:57 +0x159 fp=0xc820034c00 sp=0xc820034b80 
github.com/opencontainers/runc/libcontainer/nsenter.TestNsenterValidPaths(0xc8200b0120) 
        /mnt/tmpssd/src/PKG-GO/runc/runc-0.0.9/_build/src/github.com/opencontainers/runc/libcontainer/nsenter/nsenter_test.go:63 +0xbf7 fp=0xc820034f68 sp=0xc820034c00 
testing.tRunner(0xc8200b0120, 0xae9ae0) 
        /usr/lib/go/src/testing/testing.go:473 +0x98 fp=0xc820034fa0 sp=0xc820034f68 
runtime.goexit() 
        /usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820034fa8 sp=0xc820034fa0 
created by testing.RunTests 
        /usr/lib/go/src/testing/testing.go:582 +0x892 

goroutine 1 [chan receive]: 
testing.RunTests(0x7ef380, 0xae9ae0, 0x2, 0x2, 0x1) 
        /usr/lib/go/src/testing/testing.go:583 +0x8d2 
testing.(*M).Run(0xc820049ef8, 0xe) 
        /usr/lib/go/src/testing/testing.go:515 +0x81 
main.main() 
        github.com/opencontainers/runc/libcontainer/nsenter/_test/_testmain.go:56 +0x117 

goroutine 17 [syscall, locked to thread]: 
runtime.goexit() 
        /usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1 

rax    0x0 
rbx    0xc82005e780 
rcx    0x4970b4 
rdx    0x200 
rdi    0x4 
rsi    0xc8200a2400 
rbp    0x0 
rsp    0xc8200348f8 
r8     0x0 
r9     0x0 
r10    0x0 
r11    0x246 
r12    0x8 
r13    0x7ee10c 
r14    0xd 
r15    0x8 
rip    0x4970b2 
rflags 0x246 
cs     0x33 
fs     0x0 
gs     0x0 
*** Test killed with quit: ran too long (10m0s). 
FAIL    github.com/opencontainers/runc/libcontainer/nsenter     600.005s 
~~~~

`root` privileges required?

**Comment by cyphar** [comment]
Since `runc` requires root to run, the unit and integration tests also require root to run.

**Comment by onlyjob** [comment]
Perhaps there should be some kind of separation between tests that require root and those that don't. For instance it is a bad practice to build software with _root_ privileges hence in proper clean build environment (like on build servers) root tests are doomed to fail.

Besides it would be great if test recognise failure and abort sooner than when it is terminated by timeout...

**Comment by cyphar** [comment]
Should the tests fail if you don't have root? Or should they succeed? But it should be noted that it's simply not possible to run integration tests for a tool which requires root without root. AFAIK most of the unit tests don't require root (only the ones which test functions that require root to run require root).

But I agree that the test should've failed immediately and not timed out...

**Comment by marcosnils** [comment]
@onlyjob @cyphar please check #700
