### ISSUE TITLE
Flaky Test: TestCommandHookRunTimeout

### ISSUE THREAD

**Issue by cyphar** [opencontainers/runc#858]
This test fails on janky often enough to be annoying:

```
--- FAIL: TestCommandHookRunTimeout (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x45fc39]

goroutine 19 [running]:
testing.tRunner.func1(0xc820082990)
    /usr/local/go/src/testing/testing.go:450 +0x171
os.(*Process).signal(0x0, 0x7fdee84bf078, 0xc82000e230, 0x0, 0x0)
    /usr/local/go/src/os/exec_unix.go:40 +0x39
os.(*Process).Signal(0x0, 0x7fdee84bf078, 0xc82000e230, 0x0, 0x0)
    /usr/local/go/src/os/doc.go:51 +0x41
os.(*Process).kill(0x0, 0x0, 0x0)
    /usr/local/go/src/os/exec_posix.go:53 +0x45
os.(*Process).Kill(0x0, 0x0, 0x0)
    /usr/local/go/src/os/doc.go:36 +0x2d
github.com/opencontainers/runc/libcontainer/configs.Command.Run(0x7fff572f7d18, 0x66, 0xc82000a9a0, 0x2, 0x2, 0xc82000f700, 0x1, 0x1, 0x5ebd60, 0x1, ...)
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/configs/config.go:322 +0x3be
_/go/src/github.com/opencontainers/runc/libcontainer/configs_test.TestCommandHookRunTimeout(0xc820082990)
    /go/src/github.com/opencontainers/runc/libcontainer/configs/config_test.go:179 +0x2c1
testing.tRunner(0xc820082990, 0x6ec620)
    /usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
    /usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0x644ac8, 0x6ec500, 0xf, 0xf, 0x40fc01)
    /usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc820037ef8, 0x52b1c055)
    /usr/local/go/src/testing/testing.go:494 +0x70
main.main()
    _/go/src/github.com/opencontainers/runc/libcontainer/configs/_test/_testmain.go:84 +0x116

goroutine 20 [runnable]:
syscall.Syscall(0x0, 0x7, 0xc82003c9b0, 0x8, 0x0, 0x8, 0x0)
    /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.readlen(0x7, 0xc82003c9b0, 0x8, 0x3, 0x0, 0x0)
    /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1085 +0x4c
syscall.forkExec(0x7fff572f7d18, 0x66, 0xc82000a9a0, 0x2, 0x2, 0xc82003cb80, 0x24f, 0x0, 0x0)
    /usr/local/go/src/syscall/exec_unix.go:202 +0x567
syscall.StartProcess(0x7fff572f7d18, 0x66, 0xc82000a9a0, 0x2, 0x2, 0xc82003cb80, 0x2, 0x4, 0x0, 0x0)
    /usr/local/go/src/syscall/exec_unix.go:240 +0x6b
os.startProcess(0x7fff572f7d18, 0x66, 0xc82000a9a0, 0x2, 0x2, 0xc82003cdb8, 0x5dc5c0, 0x0, 0x0)
    /usr/local/go/src/os/exec_posix.go:45 +0x33c
os.StartProcess(0x7fff572f7d18, 0x66, 0xc82000a9a0, 0x2, 0x2, 0xc82003cdb8, 0x0, 0x0, 0x0)
    /usr/local/go/src/os/doc.go:24 +0x69
os/exec.(*Cmd).Start(0xc8200923c0, 0x0, 0x0)
    /usr/local/go/src/os/exec/exec.go:328 +0x767
os/exec.(*Cmd).Run(0xc8200923c0, 0x0, 0x0)
    /usr/local/go/src/os/exec/exec.go:255 +0x2d
os/exec.(*Cmd).CombinedOutput(0xc8200923c0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/os/exec/exec.go:424 +0x310
github.com/opencontainers/runc/libcontainer/configs.Command.Run.func1(0xc8200923c0, 0xc820010ea0)
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/configs/config.go:311 +0x52
created by github.com/opencontainers/runc/libcontainer/configs.Command.Run
    /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/configs/config.go:316 +0x2ad
FAIL    _/go/src/github.com/opencontainers/runc/libcontainer/configs    0.018s
```

**Comment by rajasec** [comment]
@cyphar 
when I run the make localtest this issue come often.

**Comment by AkihiroSuda** [comment]
Seems no longer flaky recent years
